{{ config(materialized = 'view') }}

select
    event_id,
    mission_id,
    split as dataset_split,
    c_object_type as chaser_object_type,
    risk,
    max_risk_estimate,
    max_risk_scaling,
    miss_distance,
    mahalanobis_distance,
    relative_speed,
    time_to_tca as time_to_tca_days,
    relative_position_r as relative_position_radial_meters,
    relative_position_t as relative_position_transverse_meters,
    relative_position_n as relative_position_normal_meters,
    relative_velocity_r as relative_velocity_radial_mps,
    relative_velocity_t as relative_velocity_transverse_mps,
    relative_velocity_n as relative_velocity_normal_mps,
    geocentric_latitude as geocentric_latitude_degrees,
    azimuth as relative_velocity_azimuth_degrees,
    elevation as relative_velocity_elevation_degrees,
    f10 as f10_radio_flux_index,
    f3m as f3m_81_day_running_mean_f10,
    ssn as wolf_sunspot_number,
    ap as daily_planetary_geomagnetic_amplitude_index,
    t_sigma_r as target_radial_pos_std_dev_meters,
    t_sigma_t as target_transverse_pos_std_dev_meters,
    t_sigma_n as target_normal_pos_std_dev_meters,
    t_sigma_rdot as target_radial_vel_std_dev_mps,
    t_sigma_tdot as target_transverse_vel_std_dev_mps,
    t_sigma_ndot as target_normal_vel_std_dev_mps,
    t_ct_r as target_corr_transverse_pos_radial_pos,
    t_cn_r as target_corr_normal_pos_radial_pos,
    t_cn_t as target_corr_normal_pos_transverse_pos,
    t_crdot_r as target_corr_radial_vel_radial_pos,
    t_crdot_t as target_corr_radial_vel_transverse_pos,
    t_crdot_n as target_corr_radial_vel_normal_pos,
    t_ctdot_r as target_corr_transverse_vel_radial_pos,
    t_ctdot_t as target_corr_transverse_vel_transverse_pos,
    t_ctdot_n as target_corr_transverse_vel_normal_pos,
    t_ctdot_rdot as target_corr_transverse_vel_radial_vel,
    t_cndot_r as target_corr_normal_vel_radial_pos,
    t_cndot_t as target_corr_normal_vel_transverse_pos,
    t_cndot_n as target_corr_normal_vel_normal_pos,
    t_cndot_rdot as target_corr_normal_vel_radial_vel,
    t_cndot_tdot as target_corr_normal_vel_transverse_vel,
    t_position_covariance_det as target_pos_covariance_determinant,
    t_span as target_collision_span_meters,
    t_h_apo as target_apogee_altitude_km,
    t_h_per as target_perigee_altitude_km,
    t_j2k_sma as target_j2000_semi_major_axis_km,
    t_j2k_ecc as target_j2000_eccentricity,
    t_j2k_inc as target_j2000_inclination_deg,
    t_rcs_estimate as target_radar_cross_section_sqm,
    t_cd_area_over_mass as target_ballistic_coeff_drag_sqm_per_kg,
    t_cr_area_over_mass as target_solar_rad_pressure_coeff_sqm_per_kg,
    t_sedr as target_energy_dissipation_rate_w_per_kg,
    t_actual_od_span as target_actual_od_interval_days,
    t_recommended_od_span as target_recommended_od_interval_days,
    t_obs_available as target_count_observations_available,
    t_obs_used as target_count_observations_used,
    t_residuals_accepted as target_residuals_accepted_ratio,
    t_time_lastob_start as target_days_to_last_ob_start,
    t_time_lastob_end as target_days_to_last_ob_end,
    t_weighted_rms as target_od_weighted_rms,
    c_sigma_r as chaser_radial_pos_std_dev_meters,
    c_sigma_t as chaser_transverse_pos_std_dev_meters,
    c_sigma_n as chaser_normal_pos_std_dev_meters,
    c_sigma_rdot as chaser_radial_vel_std_dev_mps,
    c_sigma_tdot as chaser_transverse_vel_std_dev_mps,
    c_sigma_ndot as chaser_normal_vel_std_dev_mps,
    c_ct_r as chaser_corr_transverse_pos_radial_pos,
    c_cn_r as chaser_corr_normal_pos_radial_pos,
    c_cn_t as chaser_corr_normal_pos_transverse_pos,
    c_crdot_r as chaser_corr_radial_vel_radial_pos,
    c_crdot_t as chaser_corr_radial_vel_transverse_pos,
    c_crdot_n as chaser_corr_radial_vel_normal_pos,
    c_ctdot_r as chaser_corr_transverse_vel_radial_pos,
    c_ctdot_t as chaser_corr_transverse_vel_transverse_pos,
    c_ctdot_n as chaser_corr_transverse_vel_normal_pos,
    c_ctdot_rdot as chaser_corr_transverse_vel_radial_vel,
    c_cndot_r as chaser_corr_normal_vel_radial_pos,
    c_cndot_t as chaser_corr_normal_vel_transverse_pos,
    c_cndot_n as chaser_corr_normal_vel_normal_pos,
    c_cndot_rdot as chaser_corr_normal_vel_radial_vel,
    c_cndot_tdot as chaser_corr_normal_vel_transverse_vel,
    c_position_covariance_det as chaser_pos_covariance_determinant,
    c_span as chaser_collision_span_meters,
    c_h_apo as chaser_apogee_altitude_km,
    c_h_per as chaser_perigee_altitude_km,
    c_j2k_sma as chaser_j2000_semi_major_axis_km,
    c_j2k_ecc as chaser_j2000_eccentricity,
    c_j2k_inc as chaser_j2000_inclination_deg,
    c_rcs_estimate as chaser_radar_cross_section_sqm,
    c_cd_area_over_mass as chaser_ballistic_coeff_drag_sqm_per_kg,
    c_cr_area_over_mass as chaser_solar_rad_pressure_coeff_sqm_per_kg,
    c_sedr as chaser_energy_dissipation_rate_w_per_kg,
    c_actual_od_span as chaser_actual_od_interval_days,
    c_recommended_od_span as chaser_recommended_od_interval_days,
    c_obs_available as chaser_count_observations_available,
    c_obs_used as chaser_count_observations_used,
    c_residuals_accepted as chaser_residuals_accepted_ratio,
    c_time_lastob_start as chaser_days_to_last_ob_start,
    c_time_lastob_end as chaser_days_to_last_ob_end,
    c_weighted_rms as chaser_od_weighted_rms
from {{ source('raw_space_traffic', 'space_conjunctions') }}