{{ config(materialized='table') }}

select 
    event_id,
    mission_id,
    dataset_split,
    chaser_object_type,
    case when chaser_object_type = 'DEBRIS' then 1 else 0 end as is_chaser_debris,
    case when chaser_object_type = 'PAYLOAD' then 1 else 0 end as is_chaser_payload,
    case when chaser_object_type = 'UNKNOWN' then 1 else 0 end as is_chaser_unknown,
    risk,
    case when risk > -4.0 then 1 else 0 end as is_current_critical_risk,
    max_risk_estimate,
    max_risk_scaling,
    time_to_tca_days,
    miss_distance,
    mahalanobis_distance,
    log10(greatest(mahalanobis_distance, 1e-11)) as log_mahalanobis,
    relative_speed,
    relative_position_radial_meters,
    relative_position_transverse_meters,
    relative_position_normal_meters,
    relative_velocity_radial_mps,
    relative_velocity_transverse_mps,
    relative_velocity_normal_mps,
    geocentric_latitude_degrees,
    relative_velocity_azimuth_degrees,
    relative_velocity_elevation_degrees,
    f10_radio_flux_index,
    case when f10_radio_flux_index is null then 1 else 0 end as is_space_weather_missing,
    f3m_81_day_running_mean_f10,
    wolf_sunspot_number,
    daily_planetary_geomagnetic_amplitude_index,
    target_radial_pos_std_dev_meters,
    target_transverse_pos_std_dev_meters,
    target_normal_pos_std_dev_meters,
    sqrt(
        power(target_radial_pos_std_dev_meters, 2) + power(chaser_radial_pos_std_dev_meters, 2) +
        power(target_transverse_pos_std_dev_meters, 2) + power(chaser_transverse_pos_std_dev_meters, 2) +
        power(target_normal_pos_std_dev_meters, 2) + power(chaser_normal_pos_std_dev_meters, 2)
    ) as combined_pos_sigma,
    target_radial_vel_std_dev_mps,
    case when target_radial_vel_std_dev_mps is not null then 1 else 0 end as has_target_velocity_covariance,
    target_transverse_vel_std_dev_mps,
    target_normal_vel_std_dev_mps,
    target_corr_transverse_pos_radial_pos,
    target_corr_normal_pos_radial_pos,
    target_corr_normal_pos_transverse_pos,
    target_corr_radial_vel_radial_pos,
    target_corr_radial_vel_transverse_pos,
    target_corr_radial_vel_normal_pos,
    target_corr_transverse_vel_radial_pos,
    target_corr_transverse_vel_transverse_pos,
    target_corr_transverse_vel_normal_pos,
    target_corr_transverse_vel_radial_vel,
    target_corr_normal_vel_radial_pos,
    target_corr_normal_vel_transverse_pos,
    target_corr_normal_vel_normal_pos,
    target_corr_normal_vel_radial_vel,
    target_corr_normal_vel_transverse_vel,
    target_pos_covariance_determinant,
    log10(greatest(target_pos_covariance_determinant, 1e-11)) as log_target_pos_det,
    chaser_radial_pos_std_dev_meters,
    chaser_transverse_pos_std_dev_meters,
    chaser_normal_pos_std_dev_meters,
    chaser_radial_vel_std_dev_mps,
    case when chaser_radial_vel_std_dev_mps is not null then 1 else 0 end as has_chaser_velocity_covariance,
    chaser_transverse_vel_std_dev_mps,
    chaser_normal_vel_std_dev_mps,
    chaser_corr_transverse_pos_radial_pos,
    chaser_corr_normal_pos_radial_pos,
    chaser_corr_normal_pos_transverse_pos,
    chaser_corr_radial_vel_radial_pos,
    chaser_corr_radial_vel_transverse_pos,
    chaser_corr_radial_vel_normal_pos,
    chaser_corr_transverse_vel_radial_pos,
    chaser_corr_transverse_vel_transverse_pos,
    chaser_corr_transverse_vel_normal_pos,
    chaser_corr_transverse_vel_radial_vel,
    chaser_corr_normal_vel_radial_pos,
    chaser_corr_normal_vel_transverse_pos,
    chaser_corr_normal_vel_normal_pos,
    chaser_corr_normal_vel_radial_vel,
    chaser_corr_normal_vel_transverse_vel,
    chaser_pos_covariance_determinant,
    log10(greatest(chaser_pos_covariance_determinant, 1e-11)) as log_chaser_pos_det,
    target_collision_span_meters,
    target_apogee_altitude_km,
    target_perigee_altitude_km,
    target_j2000_semi_major_axis_km,
    target_j2000_eccentricity,
    target_j2000_inclination_deg,
    target_radar_cross_section_sqm,
    case when target_radar_cross_section_sqm is null then 1 else 0 end as is_target_rcs_missing,
    target_ballistic_coeff_drag_sqm_per_kg,
    target_solar_rad_pressure_coeff_sqm_per_kg,
    target_energy_dissipation_rate_w_per_kg,
    target_actual_od_interval_days,
    target_recommended_od_interval_days,
    target_actual_od_interval_days / (target_recommended_od_interval_days + 1e-3) as target_od_staleness_ratio,
    target_count_observations_available,
    target_count_observations_used,
    target_count_observations_used / (target_count_observations_available + 1e-4) as target_ob_usage_ratio,
    target_residuals_accepted_ratio,
    target_days_to_last_ob_start,
    target_days_to_last_ob_end,
    target_od_weighted_rms,
    chaser_collision_span_meters,
    chaser_apogee_altitude_km,
    chaser_perigee_altitude_km,
    chaser_j2000_semi_major_axis_km,
    chaser_j2000_eccentricity,
    chaser_j2000_inclination_deg,
    chaser_radar_cross_section_sqm,
    case when chaser_radar_cross_section_sqm is null then 1 else 0 end as is_chaser_rcs_missing,
    chaser_ballistic_coeff_drag_sqm_per_kg,
    chaser_solar_rad_pressure_coeff_sqm_per_kg,
    chaser_energy_dissipation_rate_w_per_kg,
    chaser_actual_od_interval_days,
    chaser_recommended_od_interval_days,
    chaser_count_observations_available,
    chaser_count_observations_used,
    chaser_residuals_accepted_ratio,
    chaser_days_to_last_ob_start,
    chaser_days_to_last_ob_end,
    chaser_od_weighted_rms,
    (target_collision_span_meters + chaser_collision_span_meters) / (miss_distance + 1e-3) as collision_span_to_miss_ratio,
    miss_distance / (combined_pos_sigma + 1e-11) as miss_to_sigma_ratio
from {{ ref('stg_esa_conjunctions') }}